var data = [
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":5},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":1},
{axis:"Communication","value":4},
{axis:"Collaboration","value":3},
{axis:"Code Repository","value":5
},
],[{
name:"Hannah Abbott ",
major:"Computer Science",
degree:"Bachelor in Science",
interests:"I'm interested in visualization because it allows us to gain insight from complex and large data sets. I like skiing, hiking, and music.",
expectations:"Be able to tell a story through data driven document.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":1},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":8},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":1},
{axis:"Communication","value":10},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":7
},
],[{
name:"Ludo Bagman ",
major:"Machine Learning",
degree:"Master in Science",
interests:"Going to the gym",
expectations:"I wish to learn and be proficient at relevant and useful visualization tools and methods in order to be able to create vizualisations in projects and future work. ",
}]],
[[
{axis:"Information Visualisation","value":6},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":7},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":4},
{axis:"Communication","value":10},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":5
},
],[{
name:"Bathilda Bagshot ",
major:"Engineering Physics",
degree:"Bachelor in Science",
interests:"I am an Erasmus exchange student from Istanbul Technical University. I am studying Engineering Physics but I have a huge interest in programming and data science. I am taking half of my courses in machine learning, data science and artificial intelligence fields. I am familiar with Photoshop and Illustrator, done some poster works with them in the past. I like minimalist designs and making them avant-garde.",
expectations:"Representing data in a meaningful way and making understandable for everyone. Also the methods and concepts for different types of data structres.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":3},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":4},
{axis:"Communication","value":7},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":2
},
],[{
name:"Katie Bell ",
major:"Computer Science, Media Technology",
degree:"Master in Science",
interests:"Games, art",
expectations:"I expect to learn how to design an interactive graphics s.t. it is easy for the user to understand and guide through. I expect to use it to present data to the user e.g. game stats, food choices and interactive museums.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":7},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":1},
{axis:"Communication","value":4},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":7
},
],[{
name:"Cuthbert Binns",
major:"Computer Science",
degree:"Master in Science",
interests:"I enjoy doodling and bullet journaling, dancing and playing the badminton.",
expectations:"I want to acquire the skills of making informative and interactive visualizations, and would also like to add some information visualization projects to my portfolio. ",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":3},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":6
},
],[{
name:"Phineas Nigellus Black",
major:"Human-Computer Interaction",
degree:"Master in Science",
interests:"Film, music videos, skiing",
expectations:"I don’t really know yet.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":8},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":5},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":2},
{axis:"Communication","value":4},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":4
},
],[{
name:"Sirius Black",
major:"Computer Science",
degree:"Master in Science",
interests:"I'm interested in machine learning, graphics and visualization. I do also make computer games as a hobby.",
expectations:"I hope to somehow be able to apply it in conjunction with machine learning (perhaps using it to visualize machine learning data or decision making). Mostly though, it just seemed like a generally useful skill to have.",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":5},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":2},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":1},
{axis:"User Experience","value":3},
{axis:"Communication","value":8},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":3
},
],[{
name:"Amelia Bones ",
major:"Media Technology",
degree:"Master in Science",
interests:"Gym, baking cakes, socialize with friends.",
expectations:"I expect to learn how to visualize information in good and handy ways. Hopefully I can use my new learnings in some other projects and eventually in my future career.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":8},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":4},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":3},
{axis:"Communication","value":7},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":5
},
],[{
name:"Susan Bones ",
major:"Computer Science",
degree:"Master in Science",
interests:"Football, Youtube",
expectations:"I would like to create clear and fancy visulaizations of the data that I analyse and process. So I expect to learn how to be clear and efficient.",
}]],
[[
{axis:"Information Visualisation","value":7},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":4},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":8},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":2},
{axis:"Communication","value":10},
{axis:"Collaboration","value":3},
{axis:"Code Repository","value":8
},
],[{
name:"Terry Boot",
major:"Media Technology",
degree:"Master in Science",
interests:"Music, dance",
expectations:"How to, in a efficient way, visualize data. How to do that interactively rather than relying on things like infographics where the creator chooses what data to show instead of the user.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":4},
{axis:"Communication","value":10},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":4
},
],[{
name:"Lavender Brown",
major:"Media Technology",
degree:"Master in Science",
interests:"I am interested in sports (preferably hockey followed by soccer) and music.",
expectations:"I expect to learn how to use data and present it in a way so that it makes sense to other people.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":10},
{axis:"Artistic","value":8},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":7},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":2},
{axis:"Communication","value":10},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":8
},
],[{
name:"Millicent Bulstrode",
major:"Computer Science",
degree:"Master in Science",
interests:"TBD",
expectations:"I expect that I'll get knowledge about what different visualisation tools that exist as well as what one should think about when visualising data. Hopefully in my future work.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":6},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":6},
{axis:"Communication","value":9},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":6
},
],[{
name:"Charity Burbage",
major:"Media Technology",
degree:"Master in Computer Science with specialization in Interactive Media Technology",
interests:"I'm big into football. In the Swedish league Allsvenskan I follow AIK, but I also follow English club Liverpool FC tirelessly. About a year ago, I also picked up playing the guitar which has turned out to be a great hobby for me. ",
expectations:"To transform big datasets retrieved from somewhere on the web into some sort of visualization of the dataset. ",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":3},
{axis:"Communication","value":7},
{axis:"Collaboration","value":3},
{axis:"Code Repository","value":4
},
],[{
name:"Frank Bryce",
major:"Media Technology",
degree:"Master in Science",
interests:"I'm a media technology student with interests in web design/development, video, photography and graphics. In my spare time I like spending time learning graphic design, motion graphics and to become a better web designer/developer. Moreover I enjoy photography, sports and watching movies. ",
expectations:"To learn about theories and techniques behind information visualization to be able to create interactive programs for presenting data. I think this knowledge can be useful in many different situations i.e to analyze statistics and keep track of sales, especially today with big data.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":5},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":4},
{axis:"Communication","value":8},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":7
},
],[{
name:"Alecto Carrow",
major:"Media Technology",
degree:"Master in Science",
interests:"Computer games, working out, padle",
expectations:"How to handle and use big amounts of data to explain things.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":6},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":7},
{axis:"CG Programming","value":8},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":1},
{axis:"Communication","value":7},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":9
},
],[{
name:"Amycus Carrow",
major:"Computer Science",
degree:"Master in Science",
interests:"Rendering algorithms, game engine development and utility",
expectations:"Some modern visualization methods, use tools or on web pages",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":9},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":2},
{axis:"Communication","value":10},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":10
},
],[{
name:"Reginald Cattermole",
major:"Computer Science",
degree:"Master in Science",
interests:"Social interaction, Swimming, Video games, Programming, food. ",
expectations:"There have been several instances in different courses that teaches about the ability to acquire and structure data, but from the course, I wish to learn the ability to actually present it in a manner that is both intuitive and efficient. I think it is a very good skill to have in most fields within computer science today, since you will very likely be dealing with a lot of abstraction. Abstracting away unnecessary information while still keeping it wholesome is a very good ability to have. ",
}]],
[[
{axis:"Information Visualisation","value":8},
{axis:"Statistical","value":8},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":5},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":8},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":1},
{axis:"User Experience","value":2},
{axis:"Communication","value":5},
{axis:"Collaboration","value":2},
{axis:"Code Repository","value":8
},
],[{
name:"Mary Cattermole ",
major:"Computer Science, Business Administration",
degree:"Master in Science",
interests:"Travel",
expectations:"I want to learn the way to be D3 super master, and to go through challenging project with my friends ovvvvernight!",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":1},
{axis:"Computer Usage","value":3},
{axis:"Programming","value":1},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":3},
{axis:"Communication","value":9},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":1
},
],[{
name:"Cho Chang ",
major:"Statistics, Systems Engineering and Management",
degree:"Bachelor in Engineering (in my home institute)",
interests:"Listening to music",
expectations:"Learn the method of presenting ideas to end users when giving out presentation.",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":3},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":2},
{axis:"Communication","value":9},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":7
},
],[{
name:"Penelope Clearwater ",
major:"Media Technology",
degree:"Master in Science",
interests:"I am interested in all things visual. Love movies and especially video games. Got really interested in augmented reality from the Multimodal Interactions. Like web-developing in javascript with frameworks such as React and Angular. Excited to work with D3.js. ",
expectations:"I expect to be an expert in D3.js and generally get a better idea and foundation on visualizing information. Like, if I get a dataset, hopefully I will have a better mindset on how to visualize it.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":5},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":5},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":4},
{axis:"Communication","value":6},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":6
},
],[{
name:"Michael Corner",
major:"Media Technology",
degree:"Master in Science",
interests:"Music, sports, photography, games",
expectations:"How to effectively display information and make it look interesting while being interactive.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":2},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":6},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":9
},
],[{
name:"Vincent Crabbe",
major:"Computer Science",
degree:"Master in Science",
interests:"I really enjoy my studies and I'm also running a digital agency besides the studies from 2,5 years back. When I don't enjoy studying or working I like to travel, meet new people, have beers with friends and be with my family.",
expectations:"Possibly testing out working with new technologies and being able to motivate different design choices when it comes to visualizing data. The basics of what visualizations works best in what situations etc.",
}]],
[[
{axis:"Information Visualisation","value":7},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":8},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":8},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":4},
{axis:"Communication","value":5},
{axis:"Collaboration","value":2},
{axis:"Code Repository","value":9
},
],[{
name:"Colin Creevey",
major:"Media Technology",
degree:"Master in Science",
interests:"UX design, Wireframing, Programming (C, Obj-C, C++, Python), Gaming, Reading up on tech news",
expectations:"I wish to learn how to effectively visualise abstract data so as create modular interfaces that users can use to gather meaningful insights. This would greatly hep me with my current line of work as UX consultant ",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":2},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":6},
{axis:"Communication","value":9},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":5
},
],[{
name:"Fleur Delacour ",
major:"Media Technology",
degree:"Master in Science",
interests:"I'm interested in graphics, UX-UI, web dev ",
expectations:"I expect to learn how to take seemingly ordinary datasets and through visualisation make them extraordinary and insightful.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":4},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":1},
{axis:"Communication","value":6},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":7
},
],[{
name:"Amos Diggory",
major:"Computer Science",
degree:"Master in Science",
interests:"Training ",
expectations:"I'm expecting to learn in what way you should present data and the different good ways you can present data. ",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":4},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":4},
{axis:"Communication","value":6},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":6
},
],[{
name:"Albus Dumbledore",
major:"Media Technology",
degree:"Master in Science",
interests:"I am a musician beside my studies at KTH.",
expectations:"I hope to learn more about efficient visualization methods and then practice these in the projects. I'm not exactly sure how I'll use the knowledge, maybe in my future profession?",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":1},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":7},
{axis:"CG Programming","value":8},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":2},
{axis:"Communication","value":1},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":8
},
],[{
name:"Seamus Finnigan",
major:"Computer Science",
degree:"Master in Science",
interests:"Programming, Rocket League, Music",
expectations:"Cool visualizations",
}]],
[[
{axis:"Information Visualisation","value":6},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":2},
{axis:"Artistic","value":5},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":7},
{axis:"CG Programming","value":8},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":2},
{axis:"Communication","value":5},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":6
},
],[{
name:"Marcus Flint",
major:"Computer Science",
degree:"Master in Science",
interests:"Programming, video games, anything computer-related ",
expectations:"I expect to learn how to present different type of data in the best way possible",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":1},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":1},
{axis:"User Experience","value":7},
{axis:"Communication","value":7},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":4
},
],[{
name:"Filius Flitwick ",
major:"Media Technology",
degree:"Master in Science",
interests:"I love music. I play a few instruments. Photography and film as well. Any creative channels",
expectations:"I expect to learn how to effectively communicate data. Improve my design  process and discover more technologies.",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":4},
{axis:"Programming","value":4},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":1},
{axis:"Communication","value":6},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":5
},
],[{
name:"Cornelius Fudge",
major:"Systems,  Robotics and Control",
degree:"Master in Science",
interests:"My educational interests are mainly centered around autonomous systems. I like the idea of robots autonomously interacting with their environment. Thus, areas such as computer vision and machine learning is what really interests me. Apart from that I really enjoy spending time in nature and taking photos. I also enjoy doing a lot of sports and am constantly trying to improve my Swedish..",
expectations:"I usually work with a lot of data that is at times really difficult to comprehend due to a lack of intuitive insights into what the data represents. I expect to learn something about ways to visualize data in a way that it allows for an intuitive understanding of what the data represents even in complicated applications. I expect to use the knowledge from this course in presentations and projects centered around robots that will allow me to comprehensively visualize the complex mathematical stuff going on in the background.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":6},
{axis:"Computer Usage","value":6},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":5},
{axis:"Communication","value":7},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":4
},
],[{
name:"Gellert Grindelwald ",
major:"Computer Science",
degree:"Master in Science",
interests:"Cooking and sports.",
expectations:"How to present data in a Clear/fun way",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":4},
{axis:"Programming","value":5},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":1},
{axis:"Communication","value":10},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":5
},
],[{
name:"Godric Gryffindor ",
major:"Computer Science",
degree:"Master in Science",
interests:"Programming, Music/Guitar, Gaming",
expectations:"I expect to learn how to visualize data in an intriguing and user-friendly manner. This is a skill i aim to use in my future work and projects when coding websites and GUI's",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":1},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":6},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":2},
{axis:"Communication","value":8},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":7
},
],[{
name:"Rubeus Hagrid ",
major:"Computer Science",
degree:"Master in Science",
interests:"Photography, politics, news",
expectations:"How to create context from raw data, highlighting hidden connections, making information more usable and understandable. ",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":8},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":8},
{axis:"CG Programming","value":5},
{axis:"HCI programming","value":8},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":9
},
],[{
name:"Rolanda Hooch ",
major:"Computer Science",
degree:"Master in Science",
interests:"Software development, reading, gaming",
expectations:"Vast number of alternatives to present the data interactively. I want to use it for building my portfolio.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":4},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":4},
{axis:"Communication","value":9},
{axis:"Collaboration","value":4},
{axis:"Code Repository","value":6
},
],[{
name:"Helga Hufflepuff",
major:"Media Technology",
degree:"Master in Science",
interests:"Any type of development interests me a lot. I also love teaching others and making products which other people appreciate",
expectations:"How to make pretty information visualizations which conveys information in a really clear way to anyone, it should also be fun to interact with. Today I have no idea how to do anything close to this, so any step in this direction is a welcomed one!",
}]],
[[
{axis:"Information Visualisation","value":2},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":8},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":8},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":4},
{axis:"Communication","value":7},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":9
},
],[{
name:"Hermione Granger",
major:"Computer Science",
degree:"Master in Science",
interests:"Drawing",
expectations:"I want to be able to have different theories and methods I can evaluate between when choosing visualization technique in the future. For an example, how to visualize three data variables in a 2D plot.",
}]],
[[
{axis:"Information Visualisation","value":7},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":7},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":6},
{axis:"Communication","value":7},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":6
},
],[{
name:"Igor Karkaroff ",
major:"Computer Science",
degree:"Master in Science",
interests:"TBD",
expectations:"The theory and methods to develop a information chart",
}]],
[[
{axis:"Information Visualisation","value":6},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":4},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":4},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":4},
{axis:"Communication","value":10},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":7
},
],[{
name:"Viktor Krum",
major:"Computer Science",
degree:"Master in Science",
interests:"Sports and video games",
expectations:"I want to learn how to properly visualize information. I might want to work with something about it or use the knowledge in my own projects, such as a website.",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":2},
{axis:"Artistic","value":9},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":3},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":3},
{axis:"Communication","value":9},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":5
},
],[{
name:"Silvanus Kettleburn ",
major:"Media Technology",
degree:"Master in Science",
interests:"I have a BFA in electronic media, so I enjoy art a lot: Exhibitions, paintings, drawings and all the other things in that world. I also like to exercise, I ride my bicycle (not in the snow), do indoor-rowing and basic exercise.  Used to work in a huge library and learned to love old books and manuscripts with forgotten stories. I have always liked programming and therefore decided to study my masters in order to explore more and improve my skills. ",
expectations:"I want know get the knowledge to take proper decisions either collecting data and visualizing it. I would prefer to practice it and do stuff from little to big projects. I would like use it in art installations, graphic design and web pages initially, but I would like to go beyond that. ",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":7},
{axis:"CG Programming","value":5},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":5},
{axis:"Communication","value":7},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":8
},
],[{
name:"Bellatrix Lestrange",
major:"Computer Science",
degree:"Master in Science",
interests:"Creating cool shit, mostly on some sort of a computer.",
expectations:"Ways of displaying information in a way that makes it easy to take in, for both questions",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":6},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":9
},
],[{
name:"Neville Longbottom",
major:"Computer Science",
degree:"Master in Science",
interests:"Games.",
expectations:"How to create nice visuals using programming. Expect to use it to create nice products in the future.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":3},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":7},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":7},
{axis:"Communication","value":7},
{axis:"Collaboration","value":5},
{axis:"Code Repository","value":4
},
],[{
name:"Xenophilius Lovegood ",
major:"Computer Science",
degree:"Master in Science",
interests:"Video games and music",
expectations:"I expect to learn about how to visualize information in a way that is easy to understand",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":4},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":5},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":2},
{axis:"Communication","value":8},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":6
},
],[{
name:"Remus Lupin",
major:"Computer Science",
degree:"Master in Science",
interests:"Working out at the gym and playing video games. ",
expectations:"More about java script and its visual frameworks such as D3.js and also how to present data in an intuitive manner. Maybe at a future workplace. ",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":1},
{axis:"Mathematical","value":2},
{axis:"Artistic","value":1},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":9},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":8},
{axis:"User Experience","value":9},
{axis:"Communication","value":9},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":10
},
],[{
name:"Draco Malfoy",
major:"Computer Science, Human-Computer Interaction",
degree:"Master in Science",
interests:"Computer games, reading, netflix, watching Twitch streams, beer",
expectations:"To learn tools to display information further than in an infograph.",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":5},
{axis:"CG Programming","value":2},
{axis:"HCI programming","value":7},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":9},
{axis:"Code Repository","value":6
},
],[{
name:"Ernie Macmillan",
major:"Media Technology",
degree:"Master in Science",
interests:"Sports of all kinds, computer games, programming (i suppose?)",
expectations:"General good practices in info vis. Tools and utilities. Want to do something fun and creative where i put my old and newly aquired skills to use. Wanna do an awesome project to put in my portfolio. ",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":1},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":6},
{axis:"Computer Usage","value":7},
{axis:"Programming","value":2},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":5},
{axis:"Communication","value":9},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":1
},
],[{
name:"Minerva McGonagall",
major:"Human-Computer Interaction, Media Technology",
degree:"Master in Science",
interests:"I like to create and design pretty things",
expectations:"How to visualise things in a better way and also new frameworks and tools for doing so",
}]],
[[
{axis:"Information Visualisation","value":4},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":6},
{axis:"Computer Usage","value":5},
{axis:"Programming","value":6},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":5},
{axis:"Communication","value":7},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":4
},
],[{
name:"Cormac McLaggen",
major:"Data Science",
degree:"Master in Science",
interests:"Art has always fascinated me  though I am not an artist but I feel that creative minds always look at things in a very different way. Looking at the data and visualizing it in a unique way is interesting as well as exciting .  I love to cook .It is something that makes me happy . I become a creative person whenever i cook.",
expectations:"I expect to see data in a different way .I am pretty excited about this course  and its my area of interest .I feel this course will help me a lot .",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":8},
{axis:"CG Programming","value":3},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":7},
{axis:"Communication","value":8},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":9
},
],[{
name:"Graham Montague",
major:"Computer Science",
degree:"Master in Science",
interests:"I finished my bachelor's a couple of years ago and started working right away in the industry as a UI Engineer consultant focusing mainly on web technologies. I've also taken on some jobs before getting my degree but most were freelancing or volunteering. Right now I'm interested in meeting new people and sharpening my HCI-related skills. Some of my hobbies include playing music, coding, gaming, and reading.",
expectations:"Best practices when dealing with data visualization, do, don'ts, etc. Common tools, or at least the notion that they exist, to use professionally. Practical knowledge that can be applied as soon as the course is over.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":1},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":10},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":2},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":3},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":1
},
],[{
name:"Theodore Nott",
major:"Human-Computer Interaction, Media Technology",
degree:"Master in interactive media technology",
interests:"I like art and paint a lot. I have worked as a UX designer and love to create beautiful things such as logos and prototypes. I do also like front-end programming.",
expectations:"I love rhetoric and being able to influence people. I expect to be able to influence people to an even greater level with the help of visualization.",
}]],
[[
{axis:"Information Visualisation","value":3},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":3},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":8},
{axis:"CG Programming","value":5},
{axis:"HCI programming","value":5},
{axis:"User Experience","value":3},
{axis:"Communication","value":7},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":1
},
],[{
name:"Garrick Ollivander ",
major:"Computer Science",
degree:"Master in Science",
interests:"TBD",
expectations:"Honestly i expect to learn how to make computer graphics that look cool.",
}]],
[[
{axis:"Information Visualisation","value":7},
{axis:"Statistical","value":4},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":8},
{axis:"CG Programming","value":6},
{axis:"HCI programming","value":7},
{axis:"User Experience","value":4},
{axis:"Communication","value":7},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":7
},
],[{
name:"Pansy Parkinson",
major:"Computer Science",
degree:"Master in Science",
interests:"TBD",
expectations:"Representing data in a way that gives a good overview of it. Will probably be useful to know almost anywhere as so much depends on studying all the data collected.",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":7},
{axis:"Mathematical","value":8},
{axis:"Artistic","value":6},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":8},
{axis:"CG Programming","value":6},
{axis:"HCI programming","value":4},
{axis:"User Experience","value":7},
{axis:"Communication","value":10},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":8
},
],[{
name:"Peter Pettigrew ",
major:"Data Science",
degree:"Master in Science",
interests:"Travelling. Fashion.",
expectations:"Learn how to visualise data in a proper way and give more useful information. By prating and learning from the teachers and other students.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":6},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":3},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":2},
{axis:"User Experience","value":3},
{axis:"Communication","value":6},
{axis:"Collaboration","value":6},
{axis:"Code Repository","value":5
},
],[{
name:"Antioch Peverell",
major:"Computer Science, Media Technology, Mathematics, Statistics, Machine Learning",
degree:"Master in Science",
interests:"I love to watch and play football. I also like video games and how they are made. ",
expectations:"Since i'm always working with data, i'm really interested in the way of presenting it. With this course, I hope to be able to interpret some graphs more easily and to make them.",
}]],
[[
{axis:"Information Visualisation","value":1},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":7},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":9},
{axis:"Programming","value":6},
{axis:"CG Programming","value":1},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":7},
{axis:"Communication","value":7},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":4
},
],[{
name:"Irma Pince",
major:"Computer Science, Human-Computer Interaction",
degree:"Master in Science",
interests:"I like to work with more frontend-oriented technology, and in particular with solutions where I get to understand how to create something that has a high degree of usability(i.e. my interest in HCI in general).  In terms of other hobbies, I have a keen interest in films as well as football. ",
expectations:"I am interested in learning more about information visualization as I think the importance of it is growing rapidly as more and more data is available.  I expect to get more hands-on experience with creating visuals related to information visualization. I'm not sure if there are any specific 'good-practices'(I don't expect it to) but I am eager to see what research material on the topic also says.  I believe I might be able to use what I've learned in a potential future career choice. For instance if I want to learn more about Business Intelligence this could be valuable. ",
}]],
[[
{axis:"Information Visualisation","value":6},
{axis:"Statistical","value":3},
{axis:"Mathematical","value":5},
{axis:"Artistic","value":2},
{axis:"Computer Usage","value":10},
{axis:"Programming","value":10},
{axis:"CG Programming","value":8},
{axis:"HCI programming","value":6},
{axis:"User Experience","value":3},
{axis:"Communication","value":10},
{axis:"Collaboration","value":10},
{axis:"Code Repository","value":10
},
],[{
name:"Sturgis Podmore ",
major:"Computer Science, Media Technology",
degree:"Master in Science",
interests:"I'm a big data engineer (or full stack engineer) and a seasonal entrepreneur, working with industry for more than 5 years. If I'm not an engineer then I would be an adventurer. I love expedition, trekking, mountaineering, skiing, last but not the least badminton. I collect adventures' memories with gadgets from action cameras to drone videography but I don't publish them. Hopefully will publish it one day. The next big thing in my bucket is to learn yacht sailing this summer. ",
expectations:"I already have a strong practical sense on modern data warehousing and rendering on Power BI. But this course will help me on the theoretical side of visualization. ",
}]],
[[
{axis:"Information Visualisation","value":5},
{axis:"Statistical","value":5},
{axis:"Mathematical","value":6},
{axis:"Artistic","value":7},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":8},
{axis:"CG Programming","value":8},
{axis:"HCI programming","value":8},
{axis:"User Experience","value":4},
{axis:"Communication","value":7},
{axis:"Collaboration","value":7},
{axis:"Code Repository","value":9
},
],[{
name:"Poppy Pomfrey ",
major:"Media Technology",
degree:"Master in Science",
interests:"TBD",
expectations:"I would like to gather more information about how data should be structured and visualised in order to provide users with a fulfilling and insightful experience ",
}]],
[[
{axis:"Information Visualisation","value":7},
{axis:"Statistical","value":2},
{axis:"Mathematical","value":4},
{axis:"Artistic","value":10},
{axis:"Computer Usage","value":8},
{axis:"Programming","value":5},
{axis:"CG Programming","value":4},
{axis:"HCI programming","value":8},
{axis:"User Experience","value":9},
{axis:"Communication","value":8},
{axis:"Collaboration","value":8},
{axis:"Code Repository","value":7},
],[{
name:"Harry Potter ",
major:"Media Technology",
degree:"Master in Science",
interests:"TBD",
expectations:"Ledsen how to visualize heavy data in a intuitive way ",
}]],
];
